name: Update coverage data

on:
  push:
    branches: [main]

permissions:
  contents: write

# avoid two runs pushing to the same branch simultaneously
concurrency:
  group: coverage-data
  cancel-in-progress: false

jobs:
  cov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Generate Coverage Report
        run: |
          uv run pytest \
            --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov=wpt_tools \
            tests/ | tee pytest-coverage.txt

      - name: Parse coverage
        id: cov
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          hide-comment: true

      # Prepare a separate worktree for the coverage-data branch
      - name: Prepare coverage-data worktree
        run: |
          set -e
          # fetch remote branch if it exists
          git fetch origin coverage-data:coverage-data || true
          # create a clean directory for the worktree
          rm -rf coverage-wt
          # add worktree; if branch exists locally use it, otherwise create from current HEAD
          if git show-ref --verify --quiet refs/heads/coverage-data; then
            git worktree add coverage-wt coverage-data
          else
            git worktree add -b coverage-data coverage-wt
          fi

      - name: Write YAML into worktree
        run: |
          mkdir -p coverage-wt/coverage
          printf 'coverage:\n  percent: %s\n  color: %s\n' \
            '${{ steps.cov.outputs.coverage }}' \
            '${{ steps.cov.outputs.color }}' > coverage-wt/coverage/summary.yml
          echo "----- coverage-wt/coverage/summary.yml -----"
          cat coverage-wt/coverage/summary.yml

      - name: Commit to coverage-data (no PR)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: coverage-wt          # commit/push from the worktree
          file_pattern: coverage/summary.yml
          commit_message: "chore: update coverage data"
          # no 'branch:' needed because we're already on coverage-data in the worktree
          # optional: protect against rare races; turn off if you don't need it
          push_options: --force-with-lease
