name: Update coverage data
on:
  push:
    branches: [main]   # run only when main is updated

permissions:
  contents: write

jobs:
  cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Run tests
        run: |
          pytest --junitxml=pytest.xml --cov=src --cov-report=term-missing tests/ | tee pytest-coverage.txt

      - name: Parse coverage
        id: cov
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          hide-comment: true

      - name: Write YAML
        run: |
          mkdir -p coverage
          cat > coverage/summary.yml <<EOF
          coverage:
            percent: ${{ steps.cov.outputs.coverage }}
            color: ${{ steps.cov.outputs.color }}
          EOF

      - name: Commit to coverage-data branch (no PR)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: chore: update coverage data
          file_pattern: coverage/summary.yml
          branch: coverage-data
          create_branch: true